source 'http://rubygems.org'
gem 'rack',           '~> 1.0'
gem 'mongo',          '~> 1.2.4'
gem 'bson',           '~> 1.2.4'
gem 'bson_ext',       '~> 1.2.4'
gem 'plucky',         '~> 0.3.7'
gem 'activesupport',  '~> 3.0.3'
gem 'ember',          '~> 0.3.0'
gem 'mail',           '~> 2.2.9'
gem 'RubyInline',	    '~> 3.8.6'
gem 'image_science',  '~> 1.2.1'
gem 'hpricot',        '~> 0.8.3'
gem 'json',           '~> 1.5.1'
gem 'rack-contrib',   '~> 1.1.0'
gem 'linguistics',    '~> 1.0.8'
gem 'activemerchant'
gem 'activemerchant-payway', git: 'https://github.com/willcannings/activemerchant-payway.git'

group :development do
  gem 'shoulda', '>= 0'
  gem 'bundler', '~> 1.0.0'
  gem 'jeweler', '~> 1.5.1'
  gem 'rcov', '>= 0'
end
