source 'http://rubygems.org'
gem 'impromptu',      '~> 1.5.2'
gem 'rack',           '~> 1.0'
gem 'mongo',          '~> 1.2.4'
gem 'bson',           '~> 1.2.4'
gem 'bson_ext',       '~> 1.2.4'
gem 'plucky',         '~> 0.3.7'
gem 'activesupport',  '~> 3.0.3'
gem 'erubis',         '~> 2.6.6'
gem 'mail',           '~> 2.2.9'
gem 'RubyInline',			'~> 3.8.6'
gem 'image_science',  '~> 1.2.1'
gem 'hpricot',        '~> 0.8.3'
gem 'builder',        '~> 2.1.2'
gem 'ri_cal',         '~> 0.8.7'
gem 'json',           '~> 1.4.6'
gem 'rack-contrib',   '~> 1.1.0'

group :development do
  gem 'shoulda', '>= 0'
  gem 'bundler', '~> 1.0.0'
  gem 'jeweler', '~> 1.5.1'
  gem 'rcov', '>= 0'
end
