# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yodel}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Will"]
  s.date = %q{2010-11-15}
  s.description = %q{Rack based Ruby CMS}
  s.email = %q{me@willcannings.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/yodel.rb",
    "test/helper.rb",
    "test/test_yodel.rb"
  ]
  s.homepage = %q{http://github.com/yodel-cms/yodel}
  s.licenses = ["Public Domain"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby CMS}
  s.test_files = [
    "test/helper.rb",
    "test/test_yodel.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<impromptu>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rack>, ["~> 1.0"])
      s.add_runtime_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<erubis>, ["~> 2.6.6"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.2.9"])
      s.add_runtime_dependency(%q<image_science>, ["~> 1.2.1"])
      s.add_runtime_dependency(%q<hpricot>, ["~> 0.8.3"])
      s.add_runtime_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_runtime_dependency(%q<ri_cal>, ["~> 0.8.7"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<rack-contrib>, ["~> 1.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<impromptu>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rack>, ["~> 1.0"])
      s.add_runtime_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<erubis>, ["~> 2.6.6"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.2.9"])
      s.add_runtime_dependency(%q<image_science>, ["~> 1.2.1"])
      s.add_runtime_dependency(%q<hpricot>, ["~> 0.8.3"])
      s.add_runtime_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_runtime_dependency(%q<ri_cal>, ["~> 0.8.7"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<rack-contrib>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<impromptu>, ["~> 1.0"])
      s.add_dependency(%q<rack>, ["~> 1.0"])
      s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<erubis>, ["~> 2.6.6"])
      s.add_dependency(%q<mail>, ["~> 2.2.9"])
      s.add_dependency(%q<image_science>, ["~> 1.2.1"])
      s.add_dependency(%q<hpricot>, ["~> 0.8.3"])
      s.add_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_dependency(%q<ri_cal>, ["~> 0.8.7"])
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<rack-contrib>, ["~> 1.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<impromptu>, ["~> 1.0"])
      s.add_dependency(%q<rack>, ["~> 1.0"])
      s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<erubis>, ["~> 2.6.6"])
      s.add_dependency(%q<mail>, ["~> 2.2.9"])
      s.add_dependency(%q<image_science>, ["~> 1.2.1"])
      s.add_dependency(%q<hpricot>, ["~> 0.8.3"])
      s.add_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_dependency(%q<ri_cal>, ["~> 0.8.7"])
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<rack-contrib>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<impromptu>, ["~> 1.0"])
    s.add_dependency(%q<rack>, ["~> 1.0"])
    s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<erubis>, ["~> 2.6.6"])
    s.add_dependency(%q<mail>, ["~> 2.2.9"])
    s.add_dependency(%q<image_science>, ["~> 1.2.1"])
    s.add_dependency(%q<hpricot>, ["~> 0.8.3"])
    s.add_dependency(%q<builder>, ["~> 2.1.2"])
    s.add_dependency(%q<ri_cal>, ["~> 0.8.7"])
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<rack-contrib>, ["~> 1.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<impromptu>, ["~> 1.0"])
    s.add_dependency(%q<rack>, ["~> 1.0"])
    s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<erubis>, ["~> 2.6.6"])
    s.add_dependency(%q<mail>, ["~> 2.2.9"])
    s.add_dependency(%q<image_science>, ["~> 1.2.1"])
    s.add_dependency(%q<hpricot>, ["~> 0.8.3"])
    s.add_dependency(%q<builder>, ["~> 2.1.2"])
    s.add_dependency(%q<ri_cal>, ["~> 0.8.7"])
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<rack-contrib>, ["~> 1.1.0"])
  end
end

