require './pages/html_decorator'
require './pages/page'
require './pages/layout'
require './pages/form_builder'
require './pages/record_proxy_page'
require './pages/redirect_page'
require './pages/form_mailer_page'
require './pages/menu'
